import type { RuleSection } from './types';

export const rules: readonly RuleSection[] = [
  {
    id: 'bidding',
    icon: 'gavel',
    title: 'How bidding works',
    lead: 'The Paid Top is one list ordered by bid size. No auction rounds, no hidden reserve — whoever holds the larger bid holds the higher position, from the second the payment clears.',
    facts: [
      ['Ranked by', 'Bid size'],
      ['Minimum bid', "50 000 so'm"],
      ['Minimum raise', "50 000 so'm"],
      ['Position updates', 'Live'],
      ['Bid decay', 'None'],
      ['Currency', 'UZS'],
    ],
    points: [
      'There is no balance in the product. Every raise is its own card payment, charged once and applied straight to your bid — nothing of yours is ever held by the platform.',
      'A raise adds to your existing bid — bids are cumulative and do not expire.',
      'Equal bids are ordered by who reached the amount first.',
      'Clicks on your card are public but do not affect position.',
      'No position is ever stored — the list is computed from current bids, so a raise moves you the second the payment clears. The one exception is the leader’s tenure: how long the current #1 has held the top is kept and shown on their card.',
      'Payment is handled by the provider — inside Telegram or on their own secure page, depending on how you pay. The bid applies when the provider confirms it, not when you press pay.',
      'Leaving the top does not return the money — see Money is final.',
    ],
  },
  {
    id: 'votes',
    icon: 'list-checks',
    title: 'Free Top and votes',
    lead: 'The Free Top is the same list logic with a different fuel: votes, earned by doing tasks. Votes cannot be bought, sold or converted — that is what keeps the second top honest.',
    facts: [
      ['Ranked by', 'Votes'],
      ['How votes come in', 'Tasks only'],
      ['Money → votes', 'Never'],
      ['Votes → money', 'Never'],
      ['Attackable', 'No'],
    ],
    points: [
      'Every vote in your balance came from a completed task: subscribing, inviting, verifying, checking in.',
      'You choose where votes go — all of them on your own project, or spread across others.',
      'Votes given are final. There is no take-back and no decay, so the Free Top only ever grows.',
      'Rewards are fixed by the platform, not by project owners: open a project +1, follow a link +1, subscribe to a channel +2, invite a friend +3.',
      'A task reward is credited once per project. Subscriptions aren’t re-checked afterward, so votes already earned are never taken back — unsubscribing later doesn’t undo the reward.',
      'Tasks are the platform’s own list. Nobody can create, price or buy a task — that is what stops votes from having a market price.',
      'Free Top projects cannot be attacked and cannot attack. Position is only ever earned upward.',
      'A project can stand in both tops at once with two independent positions.',
      'The Free leader carries a tenure too — how long they have held #1 shows on their card, and it resets the moment someone passes them.',
    ],
  },
  {
    id: 'attacks',
    icon: 'swords',
    title: 'Attacks',
    lead: 'An attack is a raise that also costs your rival. You pay the platform once, and that one payment adds to your bid and takes the same amount off theirs — so the distance between you closes twice as fast as a plain raise. Nobody receives your money except the platform: the rival loses position, never cash.',
    facts: [
      ['You pay', 'The platform'],
      ['Your bid', '+ the amount, less on repeats'],
      ['Their bid', '− the amount'],
      ['Minimum attack', "10 000 so'm"],
      ['Same rival', '3 / day'],
      ['All rivals', '10 / day'],
    ],
    example: {
      title: 'What 500 000 so’m does',
      rows: [
        ['Before', 'Them 3 000 000 · you 2 000 000'],
        ['You pay', "500 000 so'm to the platform"],
        ['After the attack', 'Them 2 500 000 · you 2 500 000'],
        ['The same money as a raise', 'Them 3 000 000 · you 2 500 000'],
      ],
      note: 'The attack closes a gap of 1 000 000 completely. The raise only halves it — same money, twice the movement.',
    },
    points: [
      'Money never passes between people. You pay the platform, exactly as with a raise — the rival’s number falls, but nobody is paid out and nothing becomes withdrawable.',
      'Repeat attacks on the same rival pay you less. The first attack on a target credits your bid with the full amount; each further attack on that same target within 48 hours credits 15% less, down to half. Leave them alone for 48 hours and it resets to full. Their loss is always the full amount — only your gain shrinks.',
      'You cannot bankrupt anyone. A bid never falls below the higher of 50 000 so’m and half of what that project first paid in. If your amount would go past that line it is trimmed, and you are charged only for the part that lands.',
      'No attacking yourself, and no attacking the Free Top. Attacks touch money bids only — votes can never be attacked, and a Free project can neither be hit nor hit back.',
      'Everything is visible. The rival gets a bot alert naming you and the amount, and both bids change publicly in the list.',
      'An attack always asks for a second confirmation, whatever your payment settings say. It is the one action in the product you approve twice.',
      'Rules are re-checked when the payment confirms, not when you press pay. If the rival has already fallen to the floor by then, the attack is trimmed or refused and you are not charged for the missing part.',
      'Attacks cannot be undone once they land — see Money is final.',
    ],
  },
  {
    id: 'verification',
    icon: 'shield-check',
    title: 'Verification',
    status: 'planned',
    lead: 'Not live yet — verification arrives after launch. It is a badge, not a rank boost: it states that the account holding the position really controls the link.',
    facts: [
      ['Status', 'Coming later'],
      ['Cost', 'Free'],
      ['Review time', 'up to 24 h'],
      ['Valid for', '12 months'],
      ['Effect on rank', 'None'],
    ],
    points: [
      'Channels and bots: we check admin rights through the Telegram bot.',
      'Websites: a meta tag or a DNS record we hand you.',
      'Businesses: registration certificate plus a phone confirmation.',
      'A verified project that changes its link loses the badge until re-checked.',
      'Impersonating another brand removes the project from both tops and the money stays spent.',
    ],
  },
  {
    id: 'refunds',
    icon: 'receipt-text',
    title: 'Money is final',
    lead: 'Money is spent the moment it lands: a bid is already standing in the list, an attack has already hit someone. There is no holding account and no take-back — the only things that come back are our own failures.',
    facts: [
      ['Bid already live', 'Final'],
      ['Attack sent', 'Final'],
      ['Leaving the top', 'Nothing back'],
      ['Payment failed', 'Nothing charged'],
      ['Charged twice', 'Back in 3 days'],
    ],
    points: [
      'A payment that failed or never reached us changes nothing: no bid moves and, if the provider took the money anyway, it is returned automatically within 24 hours.',
      'One payment charged twice: the duplicate comes back within three working days without a request.',
      'A live bid has already bought you position and clicks. Being outbid, changing the link or deleting the project returns nothing.',
      'An attack cannot be pulled back — the rival’s number has already moved and their alert has already been sent.',
      'Votes are not money and never become money: nothing to return, exchange or transfer.',
      'A card chargeback freezes the account until the provider closes the case. Positions stay where they are; actions stop.',
      'Anything else goes through Support with the payment id from your ledger. We answer inside 24 hours, yes or no.',
    ],
  },
  {
    id: 'projects',
    icon: 'link',
    title: 'Your project',
    lead: 'Two projects per account at most: one in the Paid Top, one in the Free Top. You give a name and a link — the preview and the description are read from the link itself, so there is nothing to write.',
    facts: [
      ['Per account', '2 entries'],
      ['In the Paid Top', '1'],
      ['In the Free Top', '1'],
      ['Description', 'Read from the link'],
      ['Preview refresh', 'Manual'],
      ['Changing the link', 'Re-verification'],
    ],
    points: [
      'The preview image and the description come from the page behind your link. If the page returns nothing, the card shows a placeholder icon — publication is never blocked.',
      'One slot per top is the ceiling. A second paid entry on the same account is refused — it would let one person spread votes and bids between their own projects.',
      'The same project can hold both slots at once: a bid in Paid, votes in Free, two independent positions on two independent lists.',
      'Referral link: t.me/bidwar_bot?start=<your id>. The reward lands after the invited person’s first real action in the app, not after the click.',
      'Hidden or blocked projects leave both tops and free the slot. Nothing is returned when you delete a project yourself — see Money is final.',
    ],
  },
];
