import type { LucideIcon } from 'lucide-react';
import {
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  Banknote,
  Bot,
  Briefcase,
  CalendarCheck,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsUp,
  CircleCheckBig,
  Clock,
  Coins,
  Copy,
  CreditCard,
  Crown,
  Database,
  Ellipsis,
  ExternalLink,
  FileText,
  Folder,
  FolderPlus,
  Gavel,
  Gift,
  Globe,
  Hash,
  ImageOff,
  Info,
  Languages,
  LayoutGrid,
  LifeBuoy,
  Link,
  List,
  ListChecks,
  Lock,
  LogOut,
  Mail,
  Minus,
  Moon,
  MousePointerClick,
  Phone,
  Plus,
  ReceiptText,
  RotateCcw,
  SearchX,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  Sparkles,
  Sun,
  SunMoon,
  Swords,
  Target,
  Trash2,
  TrendingDown,
  TriangleAlert,
  Trophy,
  User,
  UserPlus,
  Vibrate,
  Vote,
  Wrench,
} from 'lucide-react';

/**
 * Явный реестр вместо динамического импорта: только так работает деревотряска.
 * Добавляя иконку в макет, добавь её сюда — иначе она не отрисуется.
 *
 * Набор — Lucide, подстановка от дизайнера: своего набора у бренда нет.
 */
export const ICONS = {
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  banknote: Banknote,
  bot: Bot,
  briefcase: Briefcase,
  'calendar-check': CalendarCheck,
  check: Check,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-up': ChevronsUp,
  'circle-check-big': CircleCheckBig,
  clock: Clock,
  coins: Coins,
  copy: Copy,
  'credit-card': CreditCard,
  crown: Crown,
  database: Database,
  ellipsis: Ellipsis,
  'external-link': ExternalLink,
  'file-text': FileText,
  folder: Folder,
  'folder-plus': FolderPlus,
  gavel: Gavel,
  gift: Gift,
  globe: Globe,
  hash: Hash,
  'image-off': ImageOff,
  info: Info,
  languages: Languages,
  'layout-grid': LayoutGrid,
  'life-buoy': LifeBuoy,
  link: Link,
  list: List,
  'list-checks': ListChecks,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  minus: Minus,
  moon: Moon,
  'mouse-pointer-click': MousePointerClick,
  phone: Phone,
  plus: Plus,
  'receipt-text': ReceiptText,
  'rotate-ccw': RotateCcw,
  'search-x': SearchX,
  send: Send,
  settings: Settings,
  'share-2': Share2,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  sun: Sun,
  'sun-moon': SunMoon,
  swords: Swords,
  target: Target,
  'trash-2': Trash2,
  'trending-down': TrendingDown,
  'triangle-alert': TriangleAlert,
  trophy: Trophy,
  user: User,
  'user-plus': UserPlus,
  vibrate: Vibrate,
  vote: Vote,
  wrench: Wrench,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
